### ISSUE TITLE
RuntimeError when initialising the OpenAI class. 

### ISSUE THREAD

**Issue by d1pankar** [guidance-ai/guidance#394]
**The bug**
Getting a `RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.` when trying to initialise the `guidance.llm`.

**To Reproduce**
Just initialise the `guidance.llms.OpenAI` like in the documentation.
```python
guidance.llm = guidance.llms.OpenAI(
    model = MODEL,
    api_key=API_KEY,
    api_version=API_VERSION,
    api_type=API_TYPE,
    api_base=API_BASE,
    deployment_id = deployment_name,
)
```

**System info:**
 - Ubuntu 20.04, Intel
 - Guidance Version: 0.0.64

**Comment by Harsha-Nori** [comment]
Hi @d1pankar, we've made significant upgrades to the library in v0.1 and now recommend using the `guidance.models.OpenAI` class instead of `guidance.llms` (and may need to update some docs). See https://github.com/guidance-ai/guidance#openai for details. Feel free to re-open if this is still an issue :)
