### ISSUE TITLE
Is this repo maintained or abandoned?

### ISSUE THREAD

**Issue by dkajtoch** [guidance-ai/guidance#419]
I noticed there are a lot of unresolved issues and PR. Lates meaningful commit was a few months ago. Is this repo alive? I would like to contribute but not sure if this is the right place 
@marcotcr @Harsha-Nori

**Comment by viral0919** [comment]
I am not 100% sure, but my guess is abandoned. It has been months since updates and it doesnt seem to work with any of the latest openai versions. I have tested all [openai ](https://pypi.org/project/openai/#history) versions from 1.0.0 and above and guidance doesnt seem to be compatible with these versions

**Comment by marcotcr** [comment]
Not abandoned! In fact we just released a major change, please see [this](https://github.com/guidance-ai/guidance/discussions/429)
