### ISSUE TITLE
relationship between underlying model quality and time to complete generation

### ISSUE THREAD

**Issue by mcapizzi-cohere** [guidance-ai/guidance#422]
This is both (1) a very naive question and (2) probably best suited for another forum, but I'll ask it anyway.

Is there a relationship between (1) the underlying quality of the LLM used and (2) the time it takes to complete the guidance query?  Take two models for example:

1. model one -> very good model that, during greedy decoding, could actually complete the desired output *without* any guidance constraining
2. model two -> a very "poor" model that can only complete the desired output *with* guidance constraining

Will one of those models complete the generation *faster*?

This question reveals my lack of detailed understanding of both (1) greedy decoding in general and (2) guidance's implementation but I'd appreciate some more intuition on the question as it will help us decide if it's "worth" using a stronger (most likely larger w.r.t. parameters) model in our application.

**Comment by marcotcr** [comment]
There is no relationship between the quality of the model and the generation time, although smaller models are usually much faster. Constrained decoding doesn't seem to impact the speed of generation for any of the models we tried, even for very complex constraints (please let us know if you find it otherwise!).
