### ISSUE TITLE
Broken tests in test_gen.py

### ISSUE THREAD

**Issue by riedgar-ms** [guidance-ai/guidance#482]
**The bug**

In the file `test_gen.py`, the tests `test_pattern_kleene` and `test_gen_vs_grammar` are both broken. Since the tests appear to be identical, this is unsurprising on some level (although this does make me unsure as to the purposes of the tests).

The test fails because one of the pieces of generated text has a newline character appended. I'm not quite sure _why_ this is happening, although when stepping through the code, I did notice that the newline character was added to the regular expression in `def regex(lm, pattern)`.

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```bash
python -m pytest tests/
```
Or, look at the GitHub Actions page.

**System info (please complete the following information):**

https://github.com/guidance-ai/guidance/actions/runs/7010776895/job/19072002556

**Comment by slundberg** [comment]
Thanks @riedgar-ms ! I just pushed a fix for this. (the fix was just to relax the tests because the real issue that is it is hard to enforce max_tokens precisely on a stateless byte-level grammar). Sometimes we go over by one token (and sometimes by more when there is no way to complete the grammar without making more tokens).
