### ISSUE TITLE
Will the <select> function support multimodal models later?

### ISSUE THREAD

**Issue by qyx1121** [guidance-ai/guidance#554]
Hi, I'm wondering if the select function will support some multimodal models later? E.g., BLIP-2 in transformers.

**Comment by slundberg** [comment]
We intend guidance to work well with multi-modal models as it matures. We just want to be careful to use generalizable abstractions that are not overly architecture specific. Can you give an example of how you are hoping to use the select? Do you mean choosing between two or more images? (I ask because this assumes the model can generate images, or at least score them)

**Comment by qyx1121** [comment]
Thanks for your response. What I meant is, for instance, providing an image and a sentence as input, then constraining the model's output to a closed set. It's just like the original use case for the select function, except that the input is multimodal. Guidance can call the LLMs from Huggingface, so I‘m interested if it could call the MLLMs from Huggingface in the future.

**Comment by slundberg** [comment]
Yes, we already support multi model gemini in VertexAI (but that remote model does not support constrained select right now). Adding support for a local model is certainly within scope and will happen at some point. PRs are welcome :)
