### ISSUE TITLE
`tests` package installed with `guidance`

### ISSUE THREAD

**Issue by vkehfdl1** [guidance-ai/guidance#618]
**The bug**
When install guidance using pypi, `tests` package installed with guidance. 
It potentially occurs error who using 'tests' folder for their test code. 

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```bash
pip install guidance
```
Then you can't import original 'tests' folder from your project root, but installed `tests` package from your lib folder.

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Mac OS
 - Guidance Version (`guidance.__version__`): 0.1.10

**Comment by riedgar-ms** [comment]
I'm not quite understanding the problem, but if you want to run tests, you need to `pip install guidance[test]`

**Comment by shawnz** [comment]
The problem is that installing the guidance package creates two packages in your site-packages folder: `guidance` (as expected) and `tests` (unexpected). I think that the `tests` directory should be excluded from the find_packages statement here: https://github.com/guidance-ai/guidance/blob/05bbed039592527cf1ae4a83ffceabc9aff42a54/setup.py#L28 but I'm not really a python packaging expert.

**Comment by shawnz** [comment]
I created PR #646 with the change suggested above

**Comment by vkehfdl1** [comment]
Thanks @shawnz !!! You fix my problem.
