### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by eyalk11** [guidance-ai/guidance#855]
**The bug**

I tried to install multiple ersions 0.1.14 and 0.1.15 and from git. import guidance didn't work in all casess!

![image](https://github.com/guidance-ai/guidance/assets/72234965/c0fb2105-467e-4082-856b-3f72c81d4383)

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
# put your code snippet here
import guidance
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.):  windows python 3.10
 - 
 - Guidance Version (`guidance.__version__`): not working

**Comment by eyalk11** [comment]
Apperently it does work in python 3.11

**Comment by Harsha-Nori** [comment]
Weird -- we run tests regularly on python 3.10 and it should run fine. It seems like from the stack trace here that you had a potentially old version of the `openai` library that maybe got updated on a reinstall?

We don't force hard dependencies on any of the platforms we support -- otherwise we'd have to force an install of openai, anthropic, transformers, llama-cpp-python, pytorch, etc. etc. even if a user only wants to use one of those models. But without having a hard dependency, it's also quite tricky to enforce minimum version numbers. 

Closing this for now as I believe it's just a openAI python library version issue (they recently made a breaking change to their API), but feel free to re-open if this continues to act up! And we'll keep brainstorming better ways of checking for/enforcing dependency versions on our end.
